spring.application.name=system-animals
spring.profiles.active=dev
spring.messages.basename=MessageValue
spring.config.import=optional:classpath:MessageValue.properties

server.port=8080
server.servlet.context-path=/api/v1
server.error.whitelabel.enabled=false
server.error.include-message=always

spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.com.system.animals=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
