spring.datasource.url=jdbc:mysql://localhost:3306/animals_db
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always

jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXNlY3VyZS1hbmQtc3Ryb25nLXNlY3JldC1rZXktZm9yLWRldmVsb3BtZW50LXZhbHVlcy1vbmx5LXpvby1zeXN0ZW0=}
jwt.expiration=${JWT_ACCESS_EXPIRATION:900000}

# Configuracion de correo. Define estos valores como variables de entorno.
spring.mail.host=${MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${MAIL_PORT:2525}
spring.mail.username=${MAIL_USERNAME:a08d83ed91aabb}
spring.mail.password=${MAIL_PASSWORD:56d051f1ab5d0f}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


verification.code.rate-limit.max-requests=${VERIFICATION_CODE_MAX_REQUESTS:3}
verification.code.rate-limit.window-minutes=${VERIFICATION_CODE_WINDOW_MINUTES:15}
